import assert from 'node:assert/strict'
import { mkdir, readFile, writeFile } from 'node:fs/promises'
import { resolve } from 'node:path'
import { chromium } from 'playwright'

const base = process.env.QUOTEFLOW_URL || 'http://127.0.0.1:4316'
const output = resolve('../../tmp/customization-qa')
await mkdir(output, { recursive: true })
const browser = await chromium.launch({ channel: process.env.QUOTEFLOW_BROWSER || 'msedge', headless: true })
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, reducedMotion: 'reduce' })
const page = await context.newPage()
const errors = []
page.on('pageerror', (error) => errors.push(error.message))
const click = (name) => page.getByRole('button', { name, exact: true }).click()
async function screenshot(name, width = 1440) {
  await page.setViewportSize({ width, height: width < 600 ? 844 : 1000 })
  await page.screenshot({ path: `${output}/${name}.png`, fullPage: true, animations: 'disabled' })
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)
  assert.equal(overflow, false, `${name}: page-wide horizontal overflow`)
}
async function data(response, code = 200) { assert.equal(response.status(), code, await response.text()); return response.json() }
async function login(role = 'admin') {
  await page.goto(base, { waitUntil: 'networkidle' })
  await page.getByRole('button', { name: 'Enter demo workspace' }).waitFor()
  await click(role); await click('Enter demo workspace')
  await page.getByRole('button', { name: 'Studio settings', exact: true }).waitFor()
}
try {
  await login()
  await click('Studio settings')
  await page.getByLabel('STUDIO NAME', { exact: true }).fill('Northstar Studio')
  await page.getByLabel('CATALOG CURRENCY').selectOption('EUR')
  await page.getByLabel('TAX LABEL').fill('VAT')
  await page.getByLabel('DEFAULT TAX %', { exact: true }).fill('20')
  await page.getByLabel('DEFAULT CONTINGENCY %', { exact: true }).fill('5')
  await page.getByLabel('REVIEW DISCOUNTS ABOVE %').fill('5')
  await page.getByLabel('PROPOSAL TITLE', { exact: true }).fill('A clear path for {client}.')
  await page.getByLabel('TERMS & START CONDITIONS').fill('Start after the approved statement of work and agreed deposit.')
  const [saved] = await Promise.all([page.waitForResponse((r) => r.url().endsWith('/studio-settings') && r.request().method() === 'PUT'), click('Save studio settings')])
  await data(saved)
  await page.reload({ waitUntil: 'networkidle' })
  assert.equal(await page.getByLabel('STUDIO NAME', { exact: true }).inputValue(), 'Northstar Studio')
  await screenshot('01-studio-settings-desktop')
  await screenshot('02-studio-settings-mobile', 390)
  const [download] = await Promise.all([page.waitForEvent('download'), click('Export template')])
  await download.saveAs(`${output}/studio-template.json`)
  const template = JSON.parse(await readFile(`${output}/studio-template.json`, 'utf8'))
  assert.equal(template.settings.currency, 'EUR')
  await page.getByLabel('Import studio template').setInputFiles({ name: 'invalid.json', mimeType: 'application/json', buffer: Buffer.from('{"invalid":true}') })
  await page.getByRole('alert').filter({ hasText: 'not a QuoteFlow studio template' }).waitFor()
  await screenshot('03-invalid-template-mobile', 390)
  await page.getByLabel('Import studio template').setInputFiles({ name: 'valid.json', mimeType: 'application/json', buffer: Buffer.from(JSON.stringify(template)) })
  await page.getByText('Template loaded for review.', { exact: false }).waitFor()

  await page.setViewportSize({ width: 1440, height: 1000 })
  await click('Service catalog')
  await page.getByRole('heading', { name: 'Price with purpose.' }).waitFor()
  await click('Add service')
  await page.getByRole('dialog').waitFor()
  assert.equal(await page.getByRole('dialog').evaluate((dialog) => dialog.contains(document.activeElement)), true)
  await page.keyboard.press('Escape')
  await page.getByRole('dialog').waitFor({ state: 'hidden' })
  assert.equal(await page.getByRole('button', { name: 'Add service', exact: true }).evaluate((button) => document.activeElement === button), true)
  await click('Add service')
  await page.getByLabel('SERVICE CODE').fill(`qa-strategy-${Date.now()}`)
  await page.getByLabel('CATEGORY', { exact: true }).fill('Strategy')
  await page.getByLabel('SERVICE NAME', { exact: true }).fill('Client strategy workshop')
  await page.getByLabel('BASE PRICE (EUR)').fill('499')
  await page.getByLabel('DESCRIPTION', { exact: true }).fill('A customer-specific strategy workshop with a documented plan.')
  await click('Save catalog version')
  await page.getByRole('dialog').waitFor({ state: 'hidden' })
  await page.getByLabel('Filter category').selectOption('Strategy')
  await page.getByText('Client strategy workshop', { exact: true }).first().waitFor()
  await screenshot('04-custom-catalog-desktop')

  // Real server fixtures for UI state/error tests; the existing journey checks intake through acceptance.
  const brief = await data(await context.request.post(`${base}/api/briefs`, { data: { company_name: 'Example Client', text: 'We need a five-page website with analytics in twelve weeks. Our budget is $20,000. Final approved copy and photography are available.' } }), 201)
  const analyzed = await data(await context.request.post(`${base}/api/briefs/${brief.id}/analyze`))
  for (const question of analyzed.clarifications) await data(await context.request.post(`${base}/api/briefs/${brief.id}/clarifications/${question.id}/answer`, { data: { answer: 'Twelve weeks; $20,000; final content supplied.' } }))
  const options = await data(await context.request.post(`${base}/api/briefs/${brief.id}/options`))
  const recommended = options.options[1]
  await page.goto(`${base}?view=studio&brief=${brief.id}`, { waitUntil: 'networkidle' })
  await page.getByRole('article', { name: 'Recommended proposal preview' }).waitFor()
  const paper = page.locator('.proposal-paper')
  assert.match(await paper.innerText(), /Northstar Studio/)
  assert.match(await paper.innerText(), /VAT \(20.00%\)/)
  const list = paper.locator('ul.paper-list').first()
  assert.equal(await list.evaluate((node) => getComputedStyle(node).listStyleType), 'disc')
  const items = await list.locator('li').evaluateAll((nodes) => nodes.map((node) => ({ top: node.getBoundingClientRect().top, bottom: node.getBoundingClientRect().bottom })))
  for (let i = 1; i < items.length; i++) assert.ok(items[i].top >= items[i-1].bottom + 6, 'Proposal list spacing collapsed')
  await screenshot('05-proposal-list-desktop')
  await screenshot('06-proposal-list-mobile', 390)
  await page.getByRole('tab', { name: /Edit scope/ }).click()
  await page.getByLabel('DISCOUNT %', { exact: true }).fill('6')
  await page.getByRole('button', { name: 'Generate PDF & review link', exact: true }).isDisabled().then((disabled) => assert.equal(disabled, true))
  await page.getByRole('button', { name: /Option 01/ }).click()
  await page.getByRole('dialog', { name: 'Keep your edits?' }).waitFor()
  await page.keyboard.press('Escape')
  assert.equal(await page.getByLabel('DISCOUNT %', { exact: true }).inputValue(), '6')
  await page.getByLabel('DISCOUNT %', { exact: true }).fill('101')
  await click('Preview price')
  await page.getByRole('alert').filter({ hasText: 'between 0 and 100' }).waitFor()
  await screenshot('07-price-error-mobile', 390)
  await page.getByLabel('DISCOUNT %', { exact: true }).fill('6')
  await click('Preview price')
  await page.getByText('Server-calculated preview', { exact: true }).waitFor()
  await page.getByLabel('DISCOUNT %', { exact: true }).fill('7')
  await page.getByText('Server-calculated preview', { exact: true }).waitFor({ state: 'hidden' })
  const [revisionResponse] = await Promise.all([page.waitForResponse((r) => r.request().method() === 'PATCH' && r.url().includes('/versions/')), click('Save as new version')])
  const revision = await data(revisionResponse)
  const root = `${base}/api/quotes/${options.quote_id}/versions/${revision.id}`
  const approval = await data(await context.request.post(root + '/submit-review'))
  await data(await context.request.post(`${base}/api/approvals/${approval.id}/decision`, { data: { decision: 'approved' } }))
  await page.reload({ waitUntil: 'networkidle' })
  await page.getByRole('button', { name: /^v4/ }).click()
  const [published] = await Promise.all([page.waitForResponse((r) => r.url().endsWith('/publish')), click('Generate PDF & review link')])
  const publication = await data(published)
  const pdf = await context.request.get(root + '/pdf')
  assert.equal(pdf.status(), 200)
  await writeFile(`${output}/customized-proposal.pdf`, await pdf.body())
  const second = await data(await context.request.post(root + '/publish'))
  assert.equal((await context.request.get(`${base}/api/portal/${publication.token}`)).status(), 410)
  const customer = await browser.newContext({ viewport: { width: 390, height: 844 } })
  const review = await customer.newPage()
  review.on('pageerror', (error) => errors.push(error.message))
  await review.goto(`${base}/portal/${second.token}`, { waitUntil: 'networkidle' })
  await review.getByRole('button', { name: 'Accept proposal' }).click()
  await review.getByRole('dialog').waitFor()
  assert.equal(await review.getByRole('dialog').evaluate((dialog) => dialog.contains(document.activeElement)), true)
  await review.keyboard.press('Escape')
  await review.getByRole('button', { name: 'Accept proposal' }).click()
  await review.getByRole('button', { name: 'Confirm response' }).click()
  await review.getByText('This review is accepted.', { exact: false }).waitFor()
  await review.screenshot({ path: `${output}/08-accepted-customer-mobile.png`, fullPage: true })
  const repeatedA = await data(await customer.request.post(`${base}/api/portal/${second.token}/response`, { data: { decision: 'accepted' } }))
  const repeatedB = await data(await customer.request.post(`${base}/api/portal/${second.token}/response`, { data: { decision: 'accepted' } }))
  assert.equal(repeatedA.handoff_id, repeatedB.handoff_id)
  await customer.close()

  await page.setViewportSize({ width: 1440, height: 1000 })
  const session = (await context.cookies()).find((cookie) => cookie.name === 'quoteflow_session')
  await click('Leave workspace')
  await page.getByRole('button', { name: 'Enter demo workspace' }).waitFor()
  assert.equal((await context.request.get(`${base}/api/auth/me`, { headers: { Cookie: `quoteflow_session=${session.value}` } })).status(), 401)
  await page.reload({ waitUntil: 'networkidle' })
  await page.getByRole('button', { name: 'Enter demo workspace' }).waitFor()
  await login('viewer')
  await click('Studio settings')
  assert.equal(await page.getByLabel('STUDIO NAME', { exact: true }).isDisabled(), true)
  await screenshot('09-viewer-settings-desktop')
  await context.request.post(`${base}/api/auth/logout`)
  await click('Briefs')
  await page.getByRole('button', { name: 'Enter demo workspace' }).waitFor()
  await page.getByRole('alert').filter({ hasText: 'session has expired' }).waitFor()
  await page.route('**/api/health', (route) => route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ status: 'ok', mode: 'CONNECTED', synthetic: false }) }))
  await page.reload({ waitUntil: 'networkidle' })
  await page.getByLabel('EMAIL', { exact: true }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Enter demo workspace' }).count(), 0)
  await screenshot('10-connected-auth-desktop')
  await page.unroute('**/api/health')
  await page.route('**/api/health', (route) => route.fulfill({ status: 503, body: 'Offline fixture' }))
  await page.reload({ waitUntil: 'networkidle' })
  await page.getByRole('alert').filter({ hasText: 'API is disconnected' }).waitFor()
  assert.equal(await page.getByRole('button', { name: 'Enter demo workspace' }).isDisabled(), true)
  await screenshot('11-offline-entry-mobile', 390)
  assert.deepEqual(errors, [])
  await writeFile(`${output}/result.json`, JSON.stringify({ passed: true, screenshots: 11, pageErrors: errors, checks: ['settings persistence', 'template import/export', 'custom categories', 'native dialog focus/Escape', 'list spacing', 'no page overflow', 'unsaved edit guard', 'pricing error and stale preview', 'PDF download', 'replaced review token', 'idempotent acceptance', 'logout revocation', 'viewer settings', 'session expiry', 'mocked connected entry', 'offline entry'] }, null, 2))
  console.log(`Customization and error UI checks passed. Evidence: ${output}`)
} finally { await browser.close() }
