"""outbox_backoff

Revision ID: 23d641a63a5f
Revises: f111a98e0e1c
Create Date: 2026-09-28 00:40:39.721044
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '23d641a63a5f'
down_revision: Union[str, None] = 'f111a98e0e1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('outbox_events', 'next_attempt_at')
    # ### end Alembic commands ###
