"""initial

Revision ID: 75a6d9e57e63
Revises:
Create Date: 2026-09-28 00:28:21.830360
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '75a6d9e57e63'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('clients',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_name', sa.String(length=160), nullable=False),
    sa.Column('contact_email', sa.String(length=250), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_workspace_id'), 'clients', ['workspace_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=False),
    sa.Column('lease_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_workspace_id'), 'jobs', ['workspace_id'], unique=False)
    op.create_table('outbox_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('idempotency_key', sa.String(length=200), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_outbox_events_workspace_id'), 'outbox_events', ['workspace_id'], unique=False)
    op.create_table('service_catalog_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'number')
    )
    op.create_index(op.f('ix_service_catalog_versions_workspace_id'), 'service_catalog_versions', ['workspace_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=False),
    sa.Column('password_hash', sa.String(length=300), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'email')
    )
    op.create_index(op.f('ix_users_workspace_id'), 'users', ['workspace_id'], unique=False)
    op.create_table('briefs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=30), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('extracted', sa.JSON(), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_briefs_client_id'), 'briefs', ['client_id'], unique=False)
    op.create_index(op.f('ix_briefs_workspace_id'), 'briefs', ['workspace_id'], unique=False)
    op.create_table('price_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('service_code', sa.String(length=60), nullable=False),
    sa.Column('rule_type', sa.String(length=30), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['service_catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_rules_version_id'), 'price_rules', ['version_id'], unique=False)
    op.create_table('service_catalog_entries',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('unit', sa.String(length=50), nullable=False),
    sa.Column('base_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['service_catalog_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version_id', 'code')
    )
    op.create_index(op.f('ix_service_catalog_entries_version_id'), 'service_catalog_entries', ['version_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('brief_revisions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('source_text', sa.Text(), nullable=False),
    sa.Column('extracted', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brief_id', 'number')
    )
    op.create_index(op.f('ix_brief_revisions_brief_id'), 'brief_revisions', ['brief_id'], unique=False)
    op.create_table('clarifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=36), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('affects', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answered_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clarifications_brief_id'), 'clarifications', ['brief_id'], unique=False)
    op.create_table('quotes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('accepted_version_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brief_id')
    )
    op.create_index('ix_quote_workspace_status', 'quotes', ['workspace_id', 'status'], unique=False)
    op.create_index(op.f('ix_quotes_brief_id'), 'quotes', ['brief_id'], unique=False)
    op.create_index(op.f('ix_quotes_client_id'), 'quotes', ['client_id'], unique=False)
    op.create_index(op.f('ix_quotes_workspace_id'), 'quotes', ['workspace_id'], unique=False)
    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('brief_id', sa.String(length=36), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=False),
    sa.Column('start', sa.Integer(), nullable=False),
    sa.Column('end', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requirements_brief_id'), 'requirements', ['brief_id'], unique=False)
    op.create_table('quote_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('quote_id', sa.String(length=36), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(length=80), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('proposal', sa.JSON(), nullable=False),
    sa.Column('catalog_version_id', sa.String(length=36), nullable=False),
    sa.Column('source_version_id', sa.String(length=36), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('tax_percent', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('contingency_percent', sa.Numeric(precision=7, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('contingency_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('approval_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['catalog_version_id'], ['service_catalog_versions.id'], ),
    sa.ForeignKeyConstraint(['quote_id'], ['quotes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_id', 'number')
    )
    op.create_index(op.f('ix_quote_versions_quote_id'), 'quote_versions', ['quote_id'], unique=False)
    op.create_table('approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('quote_version_id', sa.String(length=36), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_version_id', 'content_hash')
    )
    op.create_index(op.f('ix_approvals_quote_version_id'), 'approvals', ['quote_version_id'], unique=False)
    op.create_index(op.f('ix_approvals_workspace_id'), 'approvals', ['workspace_id'], unique=False)
    op.create_table('customer_review_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('quote_version_id', sa.String(length=36), nullable=True),
    sa.Column('brief_id', sa.String(length=36), nullable=True),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['brief_id'], ['briefs.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_customer_review_tokens_client_id'), 'customer_review_tokens', ['client_id'], unique=False)
    op.create_index(op.f('ix_customer_review_tokens_workspace_id'), 'customer_review_tokens', ['workspace_id'], unique=False)
    op.create_table('local_crm_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('quote_version_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_version_id')
    )
    op.create_index(op.f('ix_local_crm_records_client_id'), 'local_crm_records', ['client_id'], unique=False)
    op.create_index(op.f('ix_local_crm_records_workspace_id'), 'local_crm_records', ['workspace_id'], unique=False)
    op.create_table('project_handoffs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('client_id', sa.String(length=36), nullable=False),
    sa.Column('quote_version_id', sa.String(length=36), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_version_id')
    )
    op.create_index(op.f('ix_project_handoffs_client_id'), 'project_handoffs', ['client_id'], unique=False)
    op.create_index(op.f('ix_project_handoffs_workspace_id'), 'project_handoffs', ['workspace_id'], unique=False)
    op.create_table('proposal_assets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('quote_version_id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['quote_version_id'], ['quote_versions.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('quote_version_id', 'kind')
    )
    op.create_index(op.f('ix_proposal_assets_quote_version_id'), 'proposal_assets', ['quote_version_id'], unique=False)
    op.create_index(op.f('ix_proposal_assets_workspace_id'), 'proposal_assets', ['workspace_id'], unique=False)
    op.create_table('quote_lines',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('version_id', sa.String(length=36), nullable=False),
    sa.Column('service_id', sa.String(length=36), nullable=True),
    sa.Column('service_code', sa.String(length=60), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('assumption', sa.Text(), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['version_id'], ['quote_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quote_lines_version_id'), 'quote_lines', ['version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quote_lines_version_id'), table_name='quote_lines')
    op.drop_table('quote_lines')
    op.drop_index(op.f('ix_proposal_assets_workspace_id'), table_name='proposal_assets')
    op.drop_index(op.f('ix_proposal_assets_quote_version_id'), table_name='proposal_assets')
    op.drop_table('proposal_assets')
    op.drop_index(op.f('ix_project_handoffs_workspace_id'), table_name='project_handoffs')
    op.drop_index(op.f('ix_project_handoffs_client_id'), table_name='project_handoffs')
    op.drop_table('project_handoffs')
    op.drop_index(op.f('ix_local_crm_records_workspace_id'), table_name='local_crm_records')
    op.drop_index(op.f('ix_local_crm_records_client_id'), table_name='local_crm_records')
    op.drop_table('local_crm_records')
    op.drop_index(op.f('ix_customer_review_tokens_workspace_id'), table_name='customer_review_tokens')
    op.drop_index(op.f('ix_customer_review_tokens_client_id'), table_name='customer_review_tokens')
    op.drop_table('customer_review_tokens')
    op.drop_index(op.f('ix_approvals_workspace_id'), table_name='approvals')
    op.drop_index(op.f('ix_approvals_quote_version_id'), table_name='approvals')
    op.drop_table('approvals')
    op.drop_index(op.f('ix_quote_versions_quote_id'), table_name='quote_versions')
    op.drop_table('quote_versions')
    op.drop_index(op.f('ix_requirements_brief_id'), table_name='requirements')
    op.drop_table('requirements')
    op.drop_index(op.f('ix_quotes_workspace_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_client_id'), table_name='quotes')
    op.drop_index(op.f('ix_quotes_brief_id'), table_name='quotes')
    op.drop_index('ix_quote_workspace_status', table_name='quotes')
    op.drop_table('quotes')
    op.drop_index(op.f('ix_clarifications_brief_id'), table_name='clarifications')
    op.drop_table('clarifications')
    op.drop_index(op.f('ix_brief_revisions_brief_id'), table_name='brief_revisions')
    op.drop_table('brief_revisions')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_service_catalog_entries_version_id'), table_name='service_catalog_entries')
    op.drop_table('service_catalog_entries')
    op.drop_index(op.f('ix_price_rules_version_id'), table_name='price_rules')
    op.drop_table('price_rules')
    op.drop_index(op.f('ix_briefs_workspace_id'), table_name='briefs')
    op.drop_index(op.f('ix_briefs_client_id'), table_name='briefs')
    op.drop_table('briefs')
    op.drop_index(op.f('ix_users_workspace_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_service_catalog_versions_workspace_id'), table_name='service_catalog_versions')
    op.drop_table('service_catalog_versions')
    op.drop_index(op.f('ix_outbox_events_workspace_id'), table_name='outbox_events')
    op.drop_table('outbox_events')
    op.drop_index(op.f('ix_jobs_workspace_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_clients_workspace_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
